/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package config;

import Admin.adminDashboard;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MARITIME 02
 */
public class invoice extends javax.swing.JFrame {

    /**
     * Creates new form invoice
     */
    public invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        print_this = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        invoice_number = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        invoice_date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        invoice_phone_number = new javax.swing.JLabel();
        invoice_email = new javax.swing.JLabel();
        invoice_address = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        invoice_total = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        invoice_customer = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        signature_name = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        invoice_descript = new javax.swing.JLabel();
        invoice_subtotal = new javax.swing.JLabel();
        invoice_price = new javax.swing.JLabel();
        invoice_qty = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        invoice_order = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print_this.setBackground(new java.awt.Color(255, 255, 255));
        print_this.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-buy-48.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 50));

        invoice_number.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        invoice_number.setForeground(new java.awt.Color(255, 255, 255));
        invoice_number.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        invoice_number.setText("123");
        jPanel4.add(invoice_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 120, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("INVOICE");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SHOPTIFY");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 60));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("invoice no.");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 30));

        print_this.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 130));

        invoice_date.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        invoice_date.setForeground(new java.awt.Color(51, 51, 51));
        invoice_date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invoice_date.setText("10-24-2024");
        print_this.add(invoice_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, 30));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Thank you!");
        print_this.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, 100));

        invoice_phone_number.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        invoice_phone_number.setForeground(new java.awt.Color(51, 51, 51));
        invoice_phone_number.setText("09231226478");
        print_this.add(invoice_phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        invoice_email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        invoice_email.setForeground(new java.awt.Color(51, 51, 51));
        invoice_email.setText("archiealbarico@gmail.com");
        print_this.add(invoice_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        invoice_address.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        invoice_address.setForeground(new java.awt.Color(51, 51, 51));
        invoice_address.setText("Tunghaan, Minglanillla, Cebu");
        print_this.add(invoice_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("invoice to:");
        print_this.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        invoice_total.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        invoice_total.setForeground(new java.awt.Color(255, 255, 255));
        invoice_total.setText("$1,945");
        jPanel5.add(invoice_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 50));

        print_this.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 320, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        print_this.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 690, 220, 10));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        print_this.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 350, 22, 50));

        invoice_customer.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        invoice_customer.setForeground(new java.awt.Color(51, 51, 51));
        invoice_customer.setText("Archie Albarico");
        print_this.add(invoice_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        print_this.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 610, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Cash on delivery");
        print_this.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 220, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 50));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Description");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Qty");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Price");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 50));

        print_this.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 610, -1));

        signature_name.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        signature_name.setForeground(new java.awt.Color(51, 51, 51));
        signature_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signature_name.setText("Archie Albarico");
        print_this.add(signature_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 690, 220, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Payment method");
        print_this.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 220, -1));

        invoice_descript.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        invoice_descript.setForeground(new java.awt.Color(51, 51, 51));
        invoice_descript.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invoice_descript.setText("asdasdasdasdasd");
        print_this.add(invoice_descript, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 280, 50));

        invoice_subtotal.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        invoice_subtotal.setForeground(new java.awt.Color(51, 51, 51));
        invoice_subtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoice_subtotal.setText("$1,945");
        print_this.add(invoice_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 410, 60, 50));

        invoice_price.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        invoice_price.setForeground(new java.awt.Color(51, 51, 51));
        invoice_price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoice_price.setText("$1,945");
        print_this.add(invoice_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 70, 50));

        invoice_qty.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        invoice_qty.setForeground(new java.awt.Color(51, 51, 51));
        invoice_qty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoice_qty.setText("$1,945");
        print_this.add(invoice_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 70, 50));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Customer");
        print_this.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 730, 220, -1));

        invoice_order.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        invoice_order.setForeground(new java.awt.Color(51, 51, 51));
        invoice_order.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        invoice_order.setText("1234");
        print_this.add(invoice_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 320, 50, 30));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Date:");
        print_this.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 30));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("order id #");
        print_this.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        print_this.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 29, 50));

        jPanel3.add(print_this, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 670, 760));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Print invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 160, 50));

        jButton2.setBackground(new java.awt.Color(0, 158, 226));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 90, 40));

        home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(0, 158, 226));
        home.setText("INVOICE");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel3.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 40));
        animation.customizeLabel(home);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 940));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PanelPrinter panelPrinter = new PanelPrinter(print_this);
        panelPrinter.printPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked

    }//GEN-LAST:event_homeMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new invoice().setVisible(true);
                }
            });

        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(invoice.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel home;
    public javax.swing.JLabel invoice_address;
    public javax.swing.JLabel invoice_customer;
    public javax.swing.JLabel invoice_date;
    public javax.swing.JLabel invoice_descript;
    public javax.swing.JLabel invoice_email;
    public javax.swing.JLabel invoice_number;
    public javax.swing.JLabel invoice_order;
    public javax.swing.JLabel invoice_phone_number;
    public javax.swing.JLabel invoice_price;
    public javax.swing.JLabel invoice_qty;
    public javax.swing.JLabel invoice_subtotal;
    public javax.swing.JLabel invoice_total;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel print_this;
    public javax.swing.JLabel signature_name;
    // End of variables declaration//GEN-END:variables
}
